### ISSUE TITLE
Fiche complète

### ISSUE THREAD

**Issue by gildeluermoz** [PnEcrins/PatBati#6]
enlever le texte INFORMATIONS GENERALES en debut de page 1
enlever le champ Appellation dans la page 1 (car figure deja dans le bandeau)

remplacer l'etiquette coordonnée par  "Coordonnées (Lambert93)"

essayer de présenter le gros oeuvre et le second oeuvre sous forme de grid (comme travaux) ou aligné (comme equipements par exemple)

la qualité  des images est mauvaise de manière generale. dans la partie illustration du pdf, pb de taille en plus de la qualité : mettre 2 images cote a cote, de 9 cm de large (soit 1cm de marge a gauche et a droite + 1 cm entre les images au milieu de page): total 21 cm en A4

**Comment by camillemonchicourt** [comment]
Voir issue complete https://github.com/PnEcrins/PatBati/issues/7
